# Generated by Django 5.2.7 on 2025-11-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venderapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multivendors',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='multivendors',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='multivendors',
            name='user_type',
            field=models.CharField(default='vendor', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='multivendors',
            name='is_approved',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
