# Generated by Django 5.2.7 on 2025-12-12 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venderapp', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='multivendors',
            name='franchise',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_year_of_agreement', models.IntegerField()),
                ('profit_share', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchises', to='venderapp.multivendors')),
            ],
        ),
    ]
