# Generated by Django 5.2.7 on 2025-11-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venderapp', '0002_remove_multivendors_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multivendors',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
