# Generated by Django 5.2.7 on 2025-12-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venderapp', '0003_multivendors_franchise_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
