# Generated by Django 5.2.7 on 2025-12-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venderapp', '0004_remove_multivendors_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multivendors',
            name='user_type',
            field=models.CharField(default='vendor', editable=False, max_length=100),
        ),
    ]
