# Generated by Django 5.2.7 on 2025-12-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venderapp', '0005_alter_multivendors_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_img', models.ImageField(blank=True, null=True, upload_to='food_img/')),
            ],
        ),
    ]
