# Generated by Django 5.2.7 on 2025-12-17 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venderapp', '0005_alter_order_phone_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venderapp.multivendors'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='received', max_length=20),
        ),
    ]
