# Generated by Django 5.2.7 on 2025-12-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venderapp', '0006_menubuild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multivendors',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
