# Generated by Django 5.2.7 on 2025-12-03 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venderapp', '0007_alter_multivendors_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='menubuild',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='venderapp.multivendors'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menubuild',
            name='food_name',
            field=models.CharField(max_length=50),
        ),
    ]
