# Generated by Django 5.2.7 on 2025-12-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdetails',
            name='user_type',
            field=models.CharField(default='customer', editable=False, max_length=100),
        ),
    ]
