# Generated by Django 5.2.7 on 2025-12-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0002_registrationdetails_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
